# This workflows can be triggered manually via the GitHub actions UI
# It is used to trigger an integration tests run using snapshot artifacts
name: Manual Tests Run

on:
  workflow_dispatch:
    inputs:
      jahia_image:
        description: 'Jahia Image'
        required: true
        default: 'jahia/jahia-ee:8'
      tests_manifest:
        description: 'Provisioning manifest. Can be a local repository file in the tests folder or a publicly accessible link'
        required: true
        default: 'provisioning-manifest-snapshot-8.2.x.yml'

jobs:
  integration-tests:
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: ${{ github.event.inputs.jahia_image || 'ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT' }}
      module_id: saml-authentication-valve
      testrail_project: SAML Module
      pagerduty_skip_notification: true
      provisioning_manifest: ${{ github.event.inputs.provisioning_manifest || 'provisioning-manifest-snapshot-8.2.x.yml' }}
      artifact_prefix: saml

