name: Nightly (Jahia Release)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  integration-tests:
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: 'jahia/jahia-ee:8.1'
      module_id: saml-authentication-valve
      testrail_project: SAML Module
      pagerduty_skip_notification: false
      provisioning_manifest: 'provisioning-manifest-release-8.1.x.yml'
      artifact_prefix: saml
      pagerduty_incident_service: saml-authentication-valve-JahiaRL